CREATE TABLE IF NOT EXISTS predictions (

    id BIGINT
    GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,

    filename TEXT NOT NULL,

    predicted_class TEXT NOT NULL,

    confidence DOUBLE PRECISION NOT NULL,

    second_prediction TEXT,

    second_confidence DOUBLE PRECISION,

    third_prediction TEXT,

    third_confidence DOUBLE PRECISION,

    created_at TIMESTAMPTZ
    DEFAULT NOW()
);